# Copyright 2018 - 2019 Christian Müller <dev@c-mueller.xyz>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.#
kind: pipeline
name: linux-amd64

platform:
  arch: amd64
  os: linux

workspace:
  base: /go
  path: src/github.com/c-mueller/ads

steps:
  - name: load-deps
    image: golang
    commands:
      - go get -d ./...
      - go get github.com/Flaque/filet
      - go get github.com/stretchr/testify/assert
  - name: build-coredns-amd64
    image: golang
    commands:
      - cd /go/src/github.com/coredns/coredns
      - git checkout $(git describe --tags --abbrev=0)
      #- sed -i 's|hosts:hosts|ads:github.com/c-mueller/ads\nhosts:hosts|g' plugin.cfg
      - sed -i 's|loadbalance:loadbalance|ads:github.com/c-mueller/ads\nloadbalance:loadbalance|g' plugin.cfg
      - cat plugin.cfg
      - make
      - mkdir /go/src/github.com/c-mueller/ads/binaries
      - mv coredns /go/src/github.com/c-mueller/ads/binaries/coredns-ads-amd64
  - name: test
    image: golang
    secrets:
      - codecov_token
    environment:
      CODECOV_TOKEN:
        from_secret: codecov_token
    commands:
      - go test -coverprofile=coverage.txt -covermode=atomic -v ./...
      - curl -s https://codecov.io/bash | bash
  - name: build-coredns-arm
    image: golang
    environment:
      GOOS: linux
      GOARCH: arm
    commands:
      - cd /go/src/github.com/coredns/coredns
      - make
      - mv coredns /go/src/github.com/c-mueller/ads/binaries/coredns-ads-arm
  - name: build-coredns-arm64
    image: golang
    environment:
      GOOS: linux
      GOARCH: arm
    commands:
      - cd /go/src/github.com/coredns/coredns
      - make
      - mv coredns /go/src/github.com/c-mueller/ads/binaries/coredns-ads-arm64
  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files: binaries/*
    when:
      event: tag

---
kind: signature
hmac: cd28d00abfcc83fd26cc6532f7d8bb723b41e1412b45aef271a82b4d0720377f