coverage:
  range: 50..75
  round: down
  precision: 2
  status:
    patch:
      default:
        target: 60%
        threshold: 5%
        base: auto
    project:
      default:
        target: 50%
        threshold: 5%
        base: auto

comment: 
  layout: "reach, diff, flags, files" 
  behavior: default 
  require_changes: false  # if true: only post the comment if coverage changes 
  require_base: no        # [yes :: must have a base report to post] 
  require_head: yes       # [yes :: must have a head report to post] 
  branches: null 
